version: '3'

services: 
  docker:
    container_name: 'foryou'
    image: 'foryou'
    build: .
    command: bash -c "npm install && ng serve --host=0.0.0.0 --disable-host-check"
    ports:
      - "80:80"
    volumes:
      - ../:/ForYou
