version: '3'

services: 
  docker:
    container_name: 'foryou'
    image: 'foryou'
    build: .
    command: sh -c "npm install && npm start"
    ports:
      - "80:80"
    volumes:
      - ../:/ForYou
    user: "node"